version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "dockerapp"
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "dockerapp-rest-api"
    environment:
      DB_USERNAME: "admin"
      DB_PASSWORD: "admin"
      DB_DB: "testdb"
      DB_HOST: "127.0.0.1"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge